### ISSUE TITLE
Mac owncloud client 2.7 - compile error

### ISSUE THREAD

**Issue by infosteo** [owncloud/ownbuild#3]
Hello,
I am trying to compile owncloud client on a Mac using

python3 build.py --branch 2.7 -- --target 2.7 owncloud-client

as seen on:
How to build the client on Mac OS X #7965

but I'm getting this error:

[272/394] icons
**FAILED: shell_integration/MacOSX/CMakeFiles/mac_overlayplugin**
cd /Users/M2/2.7/macos-64-clang/build/owncloud/owncloud-client/work/build/shell_integration/MacOSX && xcodebuild -project /Users/M2/2.7/downloads/git/owncloud/owncloud-client/shell_integration/MacOSX/OwnCloudFinderSync/OwnCloudFinderSync.xcodeproj -target FinderSyncExt -configuration Release SYMROOT=/Users/M2/2.7/macos-64-clang/build/owncloud/owncloud-client/work/build/shell_integration/MacOSX OC_OEM_SHARE_ICNS=/Users/M2/2.7/macos-64-clang/build/owncloud/owncloud-client/work/build/src/gui/owncloud.icns OC_APPLICATION_NAME=ownCloud OC_APPLICATION_REV_DOMAIN=com.owncloud.desktopclient OC_SOCKETAPI_TEAM_IDENTIFIER_PREFIX=
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[273/394] Building CXX object test/CMakeFiles/FolderWatcherTest.dir/testfolderwatcher.cpp.o
[274/394] Building CXX object test/CMakeFiles/RemoteDiscoveryTest.dir/RemoteDiscoveryTest_autogen/mocs_compilation.cpp.o
[275/394] Building CXX object test/CMakeFiles/LockedFilesTest.dir/LockedFilesTest_autogen/mocs_compilation.cpp.o
[276/394] Building CXX object test/CMakeFiles/RemoteDiscoveryTest.dir/testremotediscovery.cpp.o
[277/394] Building CXX object test/CMakeFiles/BlacklistTest.dir/BlacklistTest_autogen/mocs_compilation.cpp.o
ninja: build stopped: subcommand failed.
**Action: compile for owncloud/owncloud-client:2.7 FAILED**
*** Craft all failed: owncloud/owncloud-client after 3 minutes 30 seconds ***
fatal error: package owncloud/owncloud-client all failed
Craft stopped with out completing ['owncloud/owncloud-client']
Command /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u /Users/M2/2.7/macos-64-clang/craft/bin/craft.py --target 2.7 owncloud-client failed with exit code: 1

**What am I doing wrong?**

Thank you.

Stefano

**Comment by infosteo** [comment]
I solved with a workaround: I put OFF in Shell integration options in cmakelists.txt 

'# this option builds the shell integration
option(BUILD_SHELL_INTEGRATION "BUILD_SHELL_INTEGRATION" **OFF**)

'# this option builds/installs the generic shell integration icons
option(BUILD_SHELL_INTEGRATION_ICONS "BUILD_SHELL_INTEGRATION_ICONS" **OFF**)

'# this options builds the dolphin integration plugin
option(BUILD_SHELL_INTEGRATION_DOLPHIN "BUILD_SHELL_INTEGRATION_DOLPHIN" **OFF**)

'# this options builds the nautilus (like) integration plugins
option(BUILD_SHELL_INTEGRATION_NAUTILUS "BUILD_SHELL_INTEGRATION_NAUTILUS" **OFF**)

**Comment by dschmidt** [comment]
The error output says it pretty clearly: `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by dschmidt** [comment]
You need to have a full xcode install to build the Finder integration. You don't need to patch the source code, just provide `-DBUILD_SHELL_INTEGRATION=OFF` to your CMake invocation.
